# Generated by Django 3.2.5 on 2021-10-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weblink',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
