# Generated by Django 3.2.5 on 2021-10-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_weblink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='weblink',
        ),
    ]
